export type Job = {
  id: string;
  title: string;
  company: string;
  companySite?: string;

  type: "Walk-in" | "Full-time" | "Internship" | "Contract";
  mode?: "Onsite" | "Hybrid" | "Remote";

  location: string;
  postedOn: string;        // ISO: YYYY-MM-DD
  eventDate?: string;      // ISO: YYYY-MM-DD (walk-ins/deadlines)
  timeWindow?: string;     // e.g., "10:00 AM – 2:00 PM"
  venue?: string;

  exp?: string;
  salary?: string;

  // Structured salary for Google JobPosting rich results (fill ONLY when the
  // employer disclosed pay — never estimate). Preferred over parsing `salary`.
  salaryMin?: number;
  salaryMax?: number;
  salaryCurrency?: string; // ISO 4217, defaults to "INR"
  salaryUnit?: "HOUR" | "DAY" | "WEEK" | "MONTH" | "YEAR"; // defaults to "YEAR"

  // Explicit application deadline → JobPosting.validThrough.
  // Falls back to eventDate, then a far-future default.
  validThrough?: string;   // ISO: YYYY-MM-DD

  highlights?: string[];
  responsibilities?: string[];

  applyEmail?: string;
  applyLink?: string;
  contacts?: string[];

  // Optional visuals/meta
  bannerImage?: string;    // e.g., "/images/jobs/qk-walkin.png"
  bannerImageAlt?: string;
  imageFallback?: string;  // used when primary image fails to load

  tags?: string[];

  // combined job title + unique id (human-readable, shareable)
  shareKey: string;
};

export const JOBS: Job[] = [
  // ======== PRIORITY: The three headline items you called out ========
  {
    id: "qualitykiosk-perf-2025-09-13",
    bannerImage: "/live-jobs_images/jobs_image/qualitykiosk-perf-2025-09-13.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Performance Tester – JMeter",
    company: "QualityKiosk Technologies Pvt. Ltd.",
    type: "Walk-in",
    mode: "Onsite",
    location: "Mumbai / Navi Mumbai",
    postedOn: "2025-09-10",
    eventDate: "2025-09-13",
    timeWindow: "10:00 AM – 2:00 PM",
    venue:
      "QualityKiosk Technologies Pvt. Ltd., F Wing, Rupa Solitaire, Millennium Business Park, Mahape, Navi Mumbai",
    exp: "1–10 yrs",
    highlights: [
      "Test Engineer / Senior Test Engineer / Associate TL / Team Lead",
      "Minimum 1–10 years in Performance Testing with JMeter",
      "Strong ability to deliver under pressure",
      "Excellent written & verbal communication; presentation skills",
    ],
    responsibilities: [
      "Analyze performance test requirements; define scenarios, workload models, KPIs",
      "Plan & execute JMeter-based performance tests",
      "Track KPIs and prepare stakeholder reports",
    ],
    applyEmail: "anisa.patel@qualitykiosk.com",
    tags: ["Job Alert", "Walk-In Drive"],
    shareKey: "performance-tester-jmeter-qualitykiosk-2025",
  },
  {
    id: "tudip-qa-2025-08-23",
    bannerImage: "/live-jobs_images/jobs_image/tudip-qa-2025-08-23.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Assurance Engineer",
    company: "Tudip Technologies (Tudip Digital AI)",
    type: "Walk-in",
    mode: "Onsite",
    location: "Pune – Hinjewadi Phase 3",
    postedOn: "2025-08-18",
    eventDate: "2025-08-23",
    timeWindow: "11:00 AM – 05:00 PM",
    venue:
      "Plot No. 11/2, Phase 3, Rajiv Gandhi Infotech Park, Hinjewadi, Pune – 411057",
    exp: "1+ yrs",
    highlights: [
      "Immediate joiner preferred",
      "Good English communication",
      "Carry a hard copy of your CV",
    ],
    responsibilities: [
      "Author & execute functional test cases and scenarios",
      "Bug reporting with repro; collaborate with devs",
      "Regression, smoke & sanity cycles",
    ],
    applyEmail: "joinus@tudip.com",
    tags: ["Job Alert", "We Are Hiring"],
    shareKey: "quality-assurance-engineer-tudip-2025",
  },
  {
    id: "avasoft-trainee-2025-08-26",
    bannerImage: "/live-jobs_images/jobs_image/avasoft-trainee-2025-08-26.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee Software Engineer",
    company: "AVASOFT",
    type: "Full-time",
    mode: "Onsite",
    location: "Chennai (Navalur)",
    postedOn: "2025-08-20",
    eventDate: "2025-08-26", // Registration closes
    timeWindow: "Selection starts 30 Aug",
    venue:
      "3rd Floor, Alphacity Beta Block, SSPDL, Navalur, Tamil Nadu – 600130",
    exp: "0–1 yr (2022–2026 passouts)",
    salary: "₹6–10 LPA (CTC)",
    highlights: [
      "Immediate Joining",
      "In-Person Written Test: 30 Aug 2025",
      "Online Tech Interview: From 1 Sep 2025",
      "Final In-Person Tech Interview: TBA",
    ],
    responsibilities: [
      "Learn & contribute to production-grade code",
      "Follow SDLC, code reviews, testing & documentation",
    ],
    applyEmail: "recruitment@avasoft.com",
    contacts: ["+91 89258 67655", "+91 89250 08708", "+91 91500 50213"],
    applyLink: "https://bit.ly/TraineeSoftwareEngineer",
    tags: ["Job Alert", "We’re Hiring"],
    shareKey: "trainee-software-engineer-avasoft-2025",
  },

  // ======== The rest of your list, normalized for the card UI ========
  {
    id: "testriq-bfsi-2025-08-11",
    bannerImage: "/live-jobs_images/jobs_image/testriq-bfsi-2025-08-11.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Test Engineer – BFSI Domain",
    company: "Testriq QA Lab (via Cinute Digital)",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-05",
    eventDate: "2025-08-11",
    timeWindow: "Final F2F on 11 Aug 2025",
    venue: "Mumbai (client site; shared post-screening)",
    exp: "0–6 yrs",
    salary: "₹3.5–8.4 LPA",
    highlights: [
      "Profiles: Manual Test Engineer | Automation Test Engineer",
      "Work From Office • 14 Open Positions",
    ],
    responsibilities: ["Virtual screening → Final face-to-face interview"],
    applyLink: "https://forms.gle/JCpZ2iR51e7FLXAM7",
    tags: ["Job Alert", "BFSI"],
    shareKey: "software-test-engineer-bfsi-testriq-2025",
  },
  {
    id: "canopus-qa-indore",
    bannerImage: "/live-jobs_images/jobs_image/canopus-qa-indore.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Assurance Engineer",
    company: "Canopus Infosystems PVT. LTD.",
    type: "Full-time",
    mode: "Onsite",
    location: "Indore",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    highlights: ["Postman", "Jira", "Confluence", "Bugzilla", "Trello"],
    venue:
      "Office 203, 2nd Floor, Princes’ Business Skypark, A.B. Road, Opp. Orbit Mall, Indore, MP – 452010",
    applyEmail: "vaibhav.shah@canopusinfosystems.com",
    shareKey: "qa-engineer-canopus-indore",
  },
  {
    id: "rekruton-qa-manual",
    bannerImage: "/live-jobs_images/jobs_image/rekruton-qa-manual.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Analyst (Manual Tester)",
    company: "RekrutON Technologies",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-05",
    exp: "2–4 yrs",
    highlights: [
      "Manual, API & Functional Testing",
      "Agile experience • Good communication",
      "Automation is a plus",
    ],
    applyLink: "https://www.rekruton.in",
    shareKey: "quality-analyst-rekruton",
  },
  {
    id: "analyticsfox-manual-airoli",
    bannerImage: "/live-jobs_images/jobs_image/analyticsfox-manual-airoli.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual Tester",
    company: "Analyticsfox Softwares Private Limited",
    type: "Full-time",
    mode: "Onsite",
    location: "Airoli, Navi Mumbai",
    postedOn: "2025-08-06",
    exp: "2–4 yrs",
    highlights: [
      "Manual testing on SFDC LOS (Salesforce Loan Origination)",
      "Testing processes, defect tracking, documentation",
      "Financial domain preferred",
    ],
    shareKey: "manual-tester-analyticsfox-airoli",
  },
  {
    id: "vervali-automation-vasai",
    bannerImage: "/live-jobs_images/jobs_image/vervali-automation-vasai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Automation Tester",
    company: "Vervali Systems Pvt. Ltd",
    type: "Full-time",
    mode: "Onsite",
    location: "Vasai, Mumbai",
    postedOn: "2025-08-06",
    exp: "1–3 yrs",
    highlights: ["Selenium WebDriver", "Java", "TestNG", "Maven", "CI/CD"],
    applyEmail: "talent@vervali.com",
    applyLink: "https://www.vervali.com",
    shareKey: "automation-tester-vervali",
  },
  {
    id: "mobidudes-qa-female",
    bannerImage: "/live-jobs_images/jobs_image/mobidudes-qa-female.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester (Female)",
    company: "Mobidudes",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-04",
    exp: "0.5–2 yrs",
    highlights: ["Immediate Joiner", "Innovate. Create. Elevate."],
    applyEmail: "hr@mobidudes.com",
    contacts: ["7898657881"],
    applyLink: "https://www.mobidudes.com",
    shareKey: "qa-tester-mobidudes",
  },
  {
    id: "delta-infosoft-manual-qa",
    bannerImage: "/live-jobs_images/jobs_image/delta-infosoft-manual-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual QA Engineer",
    company: "Delta Infosoft Pvt. Ltd.",
    type: "Full-time",
    mode: "Onsite",
    location: "Ahmedabad",
    postedOn: "2025-08-03",
    exp: "1+ yr",
    responsibilities: [
      "Execute manual test cases for web/desktop apps",
      "Report bugs; track to resolution",
      "Maintain test documentation",
    ],
    applyEmail: "hr@deltainfosoft.com",
    shareKey: "manual-qa-delta-infosoft",
  },
  {
    id: "yethi-consulting-banking-qa",
    bannerImage: "/live-jobs_images/jobs_image/yethi-consulting-banking-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA / BA / TL / Software Engineer (Banking Apps)",
    company: "Yethi Consulting",
    type: "Full-time",
    mode: "Onsite",
    location: "Bengaluru / Mumbai / Chennai / Jaipur",
    postedOn: "2025-08-02",
    exp: "2–15 yrs",
    highlights: ["Finacle", "Flexcube", "Banking Domain Testing"],
    applyEmail: "Sirisha.Vuyyuru@yethi.in",
    applyLink: "https://yethi.in/careers",
    shareKey: "yethi-banking-qa-hiring",
  },
  {
    id: "winzons-software-tester-remote",
    bannerImage: "/live-jobs_images/jobs_image/winzons-software-tester-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester (Fresher–2 yrs)",
    company: "Winzons",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-04",
    exp: "0–2 yrs",
    highlights: ["5-day week", "35% hike from current CTC (exp)"],
    applyEmail: "info.winzons@gmail.com",
    applyLink: "https://www.winzons.com",
    shareKey: "software-tester-winzons-remote",
  },
  {
    id: "digiplusit-qa-mumbai",
    bannerImage: "/live-jobs_images/jobs_image/digiplusit-qa-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester",
    company: "DigiPlusIT",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-04",
    exp: "1–2 yrs",
    highlights: ["Test automation (1 yr pref.)", "Python", "Selenium"],
    contacts: ["+91 8169263650"],
    applyEmail: "HR@DigiPlusIT.com",
    shareKey: "qa-tester-digiplusit",
  },
  {
    id: "greychain-associate-qa",
    bannerImage: "/live-jobs_images/jobs_image/greychain-associate-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Associate QA Analyst",
    company: "Grey Chain Technology",
    type: "Full-time",
    mode: "Onsite",
    location: "Delhi NCR",
    postedOn: "2025-08-03",
    exp: "2–4 yrs",
    highlights: ["Manual testing", "Agile teams", "JIRA / TestRail"],
    applyEmail: "hiring@greychaindesign.com",
    shareKey: "associate-qa-analyst-greychain",
  },
  {
    id: "prioxis-qa-eng-wfo",
    bannerImage: "/live-jobs_images/jobs_image/prioxis-qa-eng-wfo.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software QA Engineer",
    company: "Prioxis Technologies (Formerly HypeTeq Software)",
    type: "Full-time",
    mode: "Onsite",
    location: "Ahmedabad",
    postedOn: "2025-08-02",
    exp: "3–5 yrs",
    highlights: ["Manual + Automation", "Selenium / Postman / JMeter", "API"],
    applyEmail: "career@Prioxis.com",
    shareKey: "software-qa-engineer-prioxis",
  },
  {
    id: "rejolut-business-analyst",
    bannerImage: "/live-jobs_images/jobs_image/rejolut-business-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Business Analyst",
    company: "Rejolut Technology Solutions",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    exp: "1–3 yrs",
    applyLink: "https://rejolut.com/jobs/business-analyst/",
    shareKey: "business-analyst-rejolut",
  },
  {
    id: "canopus-qa-3plus-indore",
    bannerImage: "/live-jobs_images/jobs_image/canopus-qa-3plus-indore.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Assurance Engineer",
    company: "Canopus Infosystems",
    type: "Full-time",
    mode: "Onsite",
    location: "Indore",
    postedOn: "2025-08-01",
    exp: "3+ yrs",
    highlights: ["Manual Testing", "SDLC", "Good communication"],
    applyEmail: "vaibhav.shah@canopusinfosystems.com",
    shareKey: "qa-engineer-canopus-3plus",
  },
  {
    id: "wipro-test-engineer-l3-mumbai",
    bannerImage: "/live-jobs_images/jobs_image/wipro-test-engineer-l3-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Test Engineer – L3 (API Automation)",
    company: "Wipro Limited",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    exp: "3–5 yrs",
    highlights: ["Mandatory: API Automation Testing"],
    shareKey: "wipro-test-engineer-l3-api",
  },
  {
    id: "etech-qa-remote-ukshift",
    bannerImage: "/live-jobs_images/jobs_image/etech-qa-remote-ukshift.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Assurance Engineer",
    company: "Etech Global Services",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    highlights: [
      "Manual, API, Web & Mobile Testing",
      "Agile, Scrum, Load & DB Testing",
      "UK shift (12:30/1:30 PM) – Rotational",
    ],
    applyEmail: "Tech.Recruitment@etechtexas.com",
    shareKey: "qa-engineer-etech-remote",
  },
  {
    id: "games2win-qa-mobile-mumbai",
    bannerImage: "/live-jobs_images/jobs_image/games2win-qa-mobile-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Test Engineer – Mobile Games",
    company: "Games2win India Private Limited",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-02",
    exp: "3–5 yrs",
    shareKey: "qa-test-engineer-games2win",
  },
  {
    id: "lnt-data-analyst-powai",
    bannerImage: "/live-jobs_images/jobs_image/lnt-data-analyst-powai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Analyst",
    company: "Larsen & Toubro – L&T Energy Hydrocarbon",
    type: "Full-time",
    mode: "Onsite",
    location: "AMN Tower, Powai (Mumbai)",
    postedOn: "2025-06-20",
    eventDate: "2025-12-17", // End date in post
    exp: "2–5 yrs",
    highlights: ["Power BI", "SCM analytics", "Performance mgmt"],
    shareKey: "data-analyst-lnt-powai",
  },
  {
    id: "deloitte-data-analyst-intern-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/deloitte-data-analyst-intern-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Analyst (Intern)",
    company: "Deloitte",
    type: "Internship",
    mode: "Onsite",
    location: "Mumbai – I-Think",
    postedOn: "2025-08-01",
    shareKey: "data-analyst-intern-deloitte",
  },
  {
    id: "capgemini-data-analyst-mumbai",
    bannerImage: "/live-jobs_images/jobs_image/capgemini-data-analyst-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Analyst – C",
    company: "Capgemini",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    highlights: ["Data cleaning, modeling, dashboards", "Leadership & delivery"],
    shareKey: "data-analyst-capgemini-mumbai",
  },
  {
    id: "odex-software-engineer-fresher",
    bannerImage:
      "/live-jobs_images/jobs_image/odex-software-engineer-fresher.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Engineer (Fresher)",
    company: "ODeX India Solutions Pvt Ltd",
    type: "Full-time",
    mode: "Onsite",
    location: "Vikhroli, Mumbai (HO)",
    postedOn: "2025-08-01",
    exp: "0–1 yr",
    highlights: [
      "JS/Python/Java/C • HTML/CSS/React",
      "DB: MySQL/MSSQL/PostgreSQL/MongoDB",
      "Spring/Spring Boot • Git/GitHub",
    ],
    applyLink: "https://odexglobal.com/careers",
    shareKey: "software-engineer-odex-fresher",
  },
  {
    id: "healthassist-senior-lead-qa",
    bannerImage: "/live-jobs_images/jobs_image/healthassist-senior-lead-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Senior/Lead QA Tester",
    company: "Health Assist",
    type: "Full-time",
    mode: "Onsite",
    location: "Andheri (W), Mumbai",
    postedOn: "2025-08-02",
    exp: "5–7 yrs",
    responsibilities: [
      "Own QA lifecycle; establish strategies",
      "Design/implement test plans; mentor team",
      "Mobile automation; CI flows; troubleshoot",
    ],
    contacts: ["+91 9220963813"],
    shareKey: "senior-lead-qa-healthassist",
  },
  {
    id: "zynora-qa-wfh",
    bannerImage: "/live-jobs_images/jobs_image/zynora-qa-wfh.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer (Manual) – WFH",
    company: "Zynora Technologies",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-03",
    exp: "0–4 yrs",
    highlights: [
      "Test plans & cases • SDLC/STLC",
      "Smoke, Sanity, Integration, Regression",
      "Agile familiarity a plus",
    ],
    applyEmail: "hr_priya@zynora.com",
    shareKey: "qa-engineer-zynora-wfh",
  },
  {
    id: "netgains-test-engineer-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/netgains-test-engineer-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Test Engineer (Manual + Automation)",
    company: "NetGains Technologies Pvt. Ltd",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-04",
    applyLink: "https://www.netgainstechnologies.com/careers.html",
    shareKey: "test-engineer-netgains-mumbai",
  },
  {
    id: "idfcfirst-data-analyst-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/idfcfirst-data-analyst-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Analyst – CX (Digital Products)",
    company: "IDFC FIRST Bank",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-02",
    exp: "2–5 yrs",
    highlights: [
      "Adobe/CleverTap analytics, A/B tests",
      "Channel/Campaign analysis, journey optimization",
    ],
    applyLink:
      "https://careers.idfcfirstbank.com/in/en/job/P-173900/Data-Analyst-Cx",
    shareKey: "data-analyst-idfcfirst",
  },
  {
    id: "gammaedge-qa-uiux",
    bannerImage: "/live-jobs_images/jobs_image/gammaedge-qa-uiux.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "GammaEdge Technology",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    highlights: ["QA Engineer • UX/UI Designer openings"],
    contacts: ["8878811755"],
    shareKey: "qa-engineer-gammaedge",
  },
  {
    id: "arkinfosoft-qa-tester-ahmedabad",
    bannerImage:
      "/live-jobs_images/jobs_image/arkinfosoft-qa-tester-ahmedabad.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester",
    company: "ARK InfoSoft (Binary to Business)",
    type: "Full-time",
    mode: "Onsite",
    location: "Ahmedabad",
    postedOn: "2025-08-01",
    exp: "1 yr",
    applyEmail: "gayatri@arkinfosoft.in",
    contacts: ["+91 7861052007"],
    applyLink: "https://www.arkinfosoft.com",
    venue:
      "421, Zion Z1, Nr. Avalon Hotel, Sindhu Bhavan Marg, Bodakdev, Ahmedabad 380054",
    shareKey: "qa-tester-arkinfosoft",
  },
  {
    id: "blueocean-systems-st-intern-aiml",
    bannerImage:
      "/live-jobs_images/jobs_image/blueocean-systems-st-intern-aiml.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester Intern – AIML & Computer Vision",
    company: "C3D Vision (Blue Ocean Systems)",
    type: "Internship",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    exp: "0–1 yr",
    highlights: [
      "AI/ML & Computer Vision exposure",
      "Python / C++ required",
      "2–3 months; in person",
    ],
    contacts: ["+91 9833964181"],
    applyEmail: "kshama.raj@blueocean.systems",
    shareKey: "software-tester-intern-blueocean",
  },
  {
    id: "workfall-qa-remote",
    bannerImage: "/live-jobs_images/jobs_image/workfall-qa-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "Workfall",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-02",
    exp: "2–3 yrs",
    highlights: [
      "Manual & Automation • Selenium, Postman, TestNG",
      "API, regression & performance testing",
    ],
    applyEmail: "jauli.verma@workfall.com",
    shareKey: "qa-engineer-workfall-remote",
  },
  {
    id: "winfrox-manual-remote",
    bannerImage: "/live-jobs_images/jobs_image/winfrox-manual-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual Tester",
    company: "Winfrox",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-02",
    exp: "0–4 yrs",
    highlights: ["5-day week", "30% hike from current CTC", "Immediate to 15d"],
    applyEmail: "hr@winfrox.co",
    shareKey: "manual-tester-winfrox-remote",
  },
  {
    id: "techbit-quality-analyst",
    bannerImage: "/live-jobs_images/jobs_image/techbit-quality-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Analyst (Manual + Automation)",
    company: "Techbit Solutions",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    exp: "1–2 yrs",
    highlights: ["Selenium or Playwright", "Cucumber, TestNG", "SQL (DQL/DML)"],
    applyEmail: "alisha.garg@techbitsolutions.com",
    shareKey: "quality-analyst-techbit",
  },
  {
    id: "ines-partners-manual-qa-remote",
    bannerImage:
      "/live-jobs_images/jobs_image/ines-partners-manual-qa-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual QA Engineer",
    company: "Ines Partners",
    type: "Full-time",
    mode: "Remote",
    location: "Dubai / Full Remote",
    postedOn: "2025-08-01",
    exp: "3+ yrs",
    applyEmail: "fs@ines-partners.com",
    shareKey: "manual-qa-ines-partners-remote",
  },
  {
    id: "stalwart-innovations-multi-roles",
    bannerImage:
      "/live-jobs_images/jobs_image/stalwart-innovations-multi-roles.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Multiple Roles (Manual/Automation QA + DevOps + Dev)",
    company: "Stalwart Innovations",
    type: "Full-time",
    mode: "Onsite",
    location: "Noida / Pune",
    postedOn: "2025-08-01",
    exp: "3–4 yrs • Immediate joiners",
    applyEmail: "recruitment@stalwartinnovations.com",
    shareKey: "stalwart-innovations-multi-roles",
  },
  {
    id: "canopus-qa-disha-indore",
    bannerImage: "/live-jobs_images/jobs_image/canopus-qa-disha-indore.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "Canopus Infosystems",
    type: "Full-time",
    mode: "Onsite",
    location: "Indore",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    highlights: ["Postman", "Jira", "Confluence", "Bugzilla", "Trello"],
    applyEmail: "disha.dubey@canopusinfosystems.com",
    shareKey: "qa-engineer-canopus-disha",
  },
  {
    id: "odox-soft-hub-qa-analyst",
    bannerImage: "/live-jobs_images/jobs_image/odox-soft-hub-qa-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Analyst",
    company: "OdoX Soft Hub",
    type: "Full-time",
    mode: "Onsite",
    location: "Govt Cyberpark, Kozhikode",
    postedOn: "2025-08-01",
    exp: "1.5–2 yrs",
    highlights: ["Odoo exp. bonus", "Immediate joiners pref."],
    contacts: ["+91 7510 1517 92"],
    applyEmail: "hr@odoxsofthub.com",
    shareKey: "qa-analyst-odox",
  },
  {
    id: "beesolver-qa-automation",
    bannerImage: "/live-jobs_images/jobs_image/beesolver-qa-automation.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Automation Engineer",
    company: "Beesolver Technology Pvt Ltd",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-02",
    exp: "4+ yrs",
    highlights: ["Robot Framework", "Python", "API", "SQL & RDBMS"],
    applyEmail: "jbharti@beesolvertechnology.com",
    shareKey: "qa-automation-engineer-beesolver",
  },
  {
    id: "techaways-trainee-junior-st",
    bannerImage:
      "/live-jobs_images/jobs_image/techaways-trainee-junior-st.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee / Junior Software Tester",
    company: "Techaways Consulting",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    exp: "0–1 yr",
    applyEmail: "inquiry@techaways.com",
    shareKey: "trainee-junior-software-tester-techaways",
  },
  {
    id: "techabbot-qa-engineer",
    bannerImage: "/live-jobs_images/jobs_image/techabbot-qa-engineer.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "TechAbbot",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    exp: "3–4 yrs",
    applyEmail: "career@techabbot.com",
    shareKey: "qa-engineer-techabbot",
  },
  {
    id: "raftlabs-qa-contractor",
    bannerImage: "/live-jobs_images/jobs_image/raftlabs-qa-contractor.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer (Contract)",
    company: "Raftlabs",
    type: "Contract",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "2–4 yrs",
    applyEmail: "hr@raftlabs.com",
    shareKey: "qa-engineer-raftlabs-contractor",
  },
  {
    id: "sadhanait-fresher-se-pune",
    bannerImage: "/live-jobs_images/jobs_image/sadhanait-fresher-se-pune.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Engineer (Fresher)",
    company: "Sadhana IT Solutions",
    type: "Full-time",
    mode: "Onsite",
    location: "Pune",
    postedOn: "2025-08-01",
    exp: "0 yrs",
    applyEmail: "jobs@sadhanaitsolutions.com",
    highlights: ["Web/Mobile • Cloud/DevOps • Data • Best practices"],
    shareKey: "software-engineer-fresher-sadhana",
  },
  {
    id: "agreem-qa-manual",
    bannerImage: "/live-jobs_images/jobs_image/agreem-qa-manual.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Manual Tester",
    company: "AGREEM TECHNOLOGIES",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    applyEmail: "career@agreemtech.com",
    applyLink: "https://www.agreemtech.com",
    contacts: ["720300115536332"],
    shareKey: "qa-manual-agreem",
  },
  {
    id: "asvayuk-walkin-devs-panchkula",
    bannerImage:
      "/live-jobs_images/jobs_image/asvayuk-walkin-devs-panchkula.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Walk-in: MERN / PHP Laravel",
    company: "Asvayuk Technologies Pvt. Ltd.",
    type: "Walk-in",
    mode: "Onsite",
    location: "Panchkula, Haryana",
    postedOn: "2025-08-01",
    venue: "SCO-44, Sector 5-MDC, Panchkula",
    applyEmail: "hiring@asvayuktech.com",
    contacts: ["+91 77194-36332"],
    shareKey: "asvayuk-walkin",
  },
  {
    id: "ncsa-qa-flutter-0-1",
    bannerImage: "/live-jobs_images/jobs_image/ncsa-qa-flutter-0-1.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA / Flutter Developer (0.5–1 yr)",
    company: "NCSA (Neno Systems)",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    applyEmail: "Preet.rathore@nenosystems.in",
    shareKey: "ncsa-qa-flutter-junior",
  },
  {
    id: "abalobi-tester-hybrid-gauteng",
    bannerImage:
      "/live-jobs_images/jobs_image/abalobi-tester-hybrid-gauteng.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Tester",
    company: "Abalobi Solutions",
    type: "Full-time",
    mode: "Hybrid",
    location: "Midrand & Pretoria",
    postedOn: "2025-08-01",
    exp: "3–5 yrs",
    highlights: [
      "QA methodologies • Tools",
      "Automation (Selenium/JUnit/TestNG) desirable",
      "Java/C#/Python for automation",
    ],
    applyEmail: "Recruitment@abalobisolutions.co.za",
    shareKey: "tester-abalobi-gauteng",
  },
  {
    id: "cloudxperte-software-testers-aurangabad",
    bannerImage:
      "/live-jobs_images/jobs_image/cloudxperte-software-testers-aurangabad.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Testers (0–2 yrs)",
    company: "CloudXperte",
    type: "Full-time",
    mode: "Onsite",
    location: "Chhatrapati Sambhaji Nagar (Aurangabad)",
    postedOn: "2025-08-01",
    shareKey: "software-testers-cloudxperte",
  },
  {
    id: "vktechno-qa-tester-0-2",
    bannerImage: "/live-jobs_images/jobs_image/vktechno-qa-tester-0-2.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester (0–2 yrs)",
    company: "VKTechno Solutions",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    applyEmail: "hr@vktechnos.com",
    shareKey: "qa-tester-vktechno",
  },
  {
    id: "capgetree-manual-tester-remote",
    bannerImage:
      "/live-jobs_images/jobs_image/capgetree-manual-tester-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual Tester (Remote)",
    company: "Capgetree Software",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    applyEmail: "info@capgetreesoftware.com",
    shareKey: "manual-tester-capgetree-remote",
  },
  {
    id: "yalamanchili-test-engineer-nagpur",
    bannerImage:
      "/live-jobs_images/jobs_image/yalamanchili-test-engineer-nagpur.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Test Engineer",
    company: "Yalamanchili",
    type: "Full-time",
    mode: "Onsite",
    location: "Nagpur",
    postedOn: "2025-08-01",
    venue:
      "Ashok Enclave 46–48, Near Somalwar School, Trisharan Nagar, Khamla, Nagpur – 440022",
    applyEmail: "hr.nagpur@yalamanchili.in",
    shareKey: "test-engineer-yalamanchili-nagpur",
  },
  {
    id: "qapitolqa-functional-automation",
    bannerImage:
      "/live-jobs_images/jobs_image/qapitolqa-functional-automation.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Full Stack Functional / Automation Testers",
    company: "QAPITOL QA",
    type: "Full-time",
    mode: "Onsite",
    location: "India (various)",
    postedOn: "2025-08-05",
    highlights: [
      "Functional (Web+API+Mobile)",
      "Selenium+Java / Appium+Java / Rest Assured",
      "Manual API testing; strong debugging",
    ],
    applyEmail: "recruitment@qapitol.com",
    applyLink: "https://www.qapitol.com/careers/",
    shareKey: "qapitolqa-hiring",
  },
  {
    id: "growcraft-manual-testing-indore",
    bannerImage:
      "/live-jobs_images/jobs_image/growcraft-manual-testing-indore.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester / Manual Testing Engineer",
    company: "GROWCRAFT SOLUTION PVT LTD",
    type: "Full-time",
    mode: "Onsite",
    location: "Indore",
    postedOn: "2025-08-01",
    exp: "0.6–1 yr",
    applyEmail: "info@growcraftsolution.com",
    contacts: ["8602431591"],
    venue:
      "Behind C21 Mall, NRK Bizz Park 5th floor, 508 Vijay Nagar, Indore (MP)",
    shareKey: "manual-testing-growcraft-indore",
  },
  {
    id: "plannet-aem-qa-walkin-mumbai-2025-03-01",
    bannerImage:
      "/live-jobs_images/jobs_image/plannet-aem-qa-walkin-mumbai-2025-03-01.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "AEM QA (Website Manual & Cross-Browser) – Walk-in",
    company: "PLAN.NET TECHNEST INDIA",
    type: "Walk-in",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-02-20",
    eventDate: "2025-03-01",
    timeWindow: "9:00 AM – 3:00 PM",
    venue:
      "10th Floor, Times Square, Tower C, Opp. Mittal Estate, Marol Naka, Andheri East, Mumbai 400059",
    highlights: ["3+ yrs experience", "10 positions"],
    applyLink: "https://www.house-of-communication.com",
    shareKey: "aem-qa-walkin-plan-net-2025",
  },
  {
    id: "techtorch-qa-engineer-remote",
    bannerImage:
      "/live-jobs_images/jobs_image/techtorch-qa-engineer-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer (Manual)",
    company: "TechTorch",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "0–4 yrs",
    applyEmail: "hr@techtorch.com",
    shareKey: "qa-engineer-techtorch-remote",
  },
  {
    id: "bnp-paribas-test-analyst-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/bnp-paribas-test-analyst-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Test Analyst – Manual Testing",
    company: "BNP Paribas",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-03",
    highlights: ["Permanent • Full-time • IT"],
    shareKey: "test-analyst-bnp-manual",
  },
  {
    id: "coversure-data-analyst-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/coversure-data-analyst-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Analyst",
    company: "CoverSure (Insurtech)",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2024-09-25",
    exp: "1–3 yrs",
    highlights: ["Product/Marketing/Risk analytics", "SQL • Python • BI"],
    shareKey: "data-analyst-coversure-mumbai",
  },
  {
    id: "qamentor-qa-tester-fresher",
    bannerImage:
      "/live-jobs_images/jobs_image/qamentor-qa-tester-fresher.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester (Fresher / College Graduates)",
    company: "QA Mentor",
    type: "Full-time",
    mode: "Onsite",
    location: "Pune / Bengaluru",
    postedOn: "2025-08-01",
    applyEmail: "jobs@qamentor.com",
    shareKey: "qa-tester-qamentor-fresher",
  },
  {
    id: "terragig-junior-qa-remote",
    bannerImage:
      "/live-jobs_images/jobs_image/terragig-junior-qa-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Junior QA (Manual + Basic Automation)",
    company: "TerraGig Consulting",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "1–2 yrs",
    applyEmail: "hr@terragigconsulting.in",
    shareKey: "junior-qa-terragig-remote",
  },
  {
    id: "3i-infotech-finnone-automation",
    bannerImage:
      "/live-jobs_images/jobs_image/3i-infotech-finnone-automation.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester – Automation (FinnOne)",
    company: "3i Infotech",
    type: "Full-time",
    mode: "Onsite",
    location: "Airoli / Goregaon / Thane",
    postedOn: "2025-08-01",
    exp: "3–5 yrs",
    applyEmail: "infantajay@3i-infotech.com",
    shareKey: "qa-automation-finnone-3i",
  },
  {
    id: "wanbuffer-qa-engineer-ahmedabad",
    bannerImage:
      "/live-jobs_images/jobs_image/wanbuffer-qa-engineer-ahmedabad.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "Wanbuffer",
    type: "Full-time",
    mode: "Onsite",
    location: "C.G. Road, Ahmedabad",
    postedOn: "2025-08-01",
    exp: "1–2 yrs",
    applyEmail: "hr@wanbuffer.in",
    applyLink: "https://www.wanbuffer.com",
    shareKey: "qa-engineer-wanbuffer",
  },
  {
    id: "omex-qa-automation-senior",
    bannerImage: "/live-jobs_images/jobs_image/omex-qa-automation-senior.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual & Automation Testing",
    company: "Omex Infotech",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    exp: "7–10 yrs",
    highlights: [
      "API Automation • Cypress • JavaScript",
      "Postman • JIRA/TestRail",
    ],
    contacts: ["+91 70480 00044"],
    applyEmail: "info@omexinfotech.com",
    shareKey: "manual-automation-omex",
  },
  {
    id: "breawapps-manual-remote",
    bannerImage:
      "/live-jobs_images/jobs_image/breawapps-manual-remote.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual Tester (Remote)",
    company: "Breawapps",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    postedOn: "2025-08-01",
    exp: "0–2 yrs",
    highlights: ["Immediate–15 days", "40% hike from current CTC"],
    applyEmail: "hr@breawappsn.com",
    shareKey: "manual-tester-breawapps-remote",
  },
  {
    id: "sigma-tech-india-assoc-manual",
    bannerImage:
      "/live-jobs_images/jobs_image/sigma-tech-india-assoc-manual.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Associate Manual Tester (QA Engineer)",
    company: "Sigma Technology India",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    exp: "0–3 yrs",
    applyEmail: "hr@ubisofts.com",
    shareKey: "associate-manual-tester-sigma",
  },
  {
    id: "letese-application-tester-noida",
    bannerImage:
      "/live-jobs_images/jobs_image/letese-application-tester-noida.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Application Tester",
    company: "Letese (via Goup Consultancy)",
    type: "Full-time",
    mode: "Onsite",
    location: "Noida (Iconic Tower, Sec-62)",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    highlights: ["Selenium or similar", "Java / Python / JS", "Agile, JIRA"],
    applyEmail: "hr@goupconsultancy.com",
    contacts: ["+91 9560035767"],
    shareKey: "application-tester-letese-noida",
  },
  {
    id: "aham-health-manual-testers",
    bannerImage:
      "/live-jobs_images/jobs_image/aham-health-manual-testers.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual Testers (0–2 yrs)",
    company: "Aham Health",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    highlights:
      ["Execute cases • Document defects • Regression • Scrum"],
    shareKey: "manual-testers-aham-health",
  },
  {
    id: "qualitykiosk-telecom-testers",
    bannerImage:
      "/live-jobs_images/jobs_image/qualitykiosk-telecom-testers.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Software Testers – Telecom Domain (OSS/BSS)",
    company: "QualityKiosk",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai (WFO)",
    postedOn: "2025-08-01",
    exp: "1–5 yrs",
    highlights: ["OSS/BSS • SIP/IMS/LTE/5G • HP Octane/JIRA"],
    applyEmail: "sunil.nagraj@qualitykiosk.com",
    shareKey: "software-testers-telecom-qualitykiosk",
  },
  {
    id: "qualitykiosk-manual-automation-campus",
    bannerImage:
      "/live-jobs_images/jobs_image/qualitykiosk-manual-automation-campus.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Manual & Automation Testing (Campus)",
    company: "QualityKiosk",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai (Western, Central, Navi Mumbai)",
    postedOn: "2025-08-01",
    venue:
      "C Wing, Rupa Solitaire, Sector-1, Millennium Business Park, 4th Floor, Kopar-Khairane, Navi Mumbai 400710",
    highlights: ["BE/BTech 2022–2024 • 60%+ throughout • No live KT"],
    contacts: ["022 4128 8200"],
    applyEmail: "Campus@qualitykiosk.com",
    applyLink: "https://www.qualitykiosk.com",
    shareKey: "manual-automation-qualitykiosk-campus",
  },
  {
    id: "general-mills-business-analyst-powai",
    bannerImage:
      "/live-jobs_images/jobs_image/general-mills-business-analyst-powai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Sr. D&T Analyst – Business Intelligence",
    company: "General Mills",
    type: "Full-time",
    mode: "Onsite",
    location: "Powai (Mumbai)",
    postedOn: "2025-08-01",
    shareKey: "business-analyst-general-mills-powai",
  },
  {
    id: "f60host-business-analyst-charniroad",
    bannerImage:
      "/live-jobs_images/jobs_image/f60host-business-analyst-charniroad.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Business Analyst",
    company: "F60 Host LLP",
    type: "Full-time",
    mode: "Onsite",
    location: "Charni Road, Mumbai",
    postedOn: "2025-08-01",
    shareKey: "business-analyst-f60host",
  },
  {
    id: "brilino-business-analyst-vikhroli",
    bannerImage:
      "/live-jobs_images/jobs_image/brilino-business-analyst-vikhroli.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Business Analyst (6-month)",
    company: "Brilino Solutions",
    type: "Contract",
    mode: "Onsite",
    location: "Vikhroli West, Mumbai",
    postedOn: "2024-12-02",
    salary: "₹15,000 / month",
    shareKey: "business-analyst-brilino-intern",
  },
  {
    id: "mira-road-java-automation-intern",
    bannerImage:
      "/live-jobs_images/jobs_image/mira-road-java-automation-intern.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Java Automation Test Engineer (Intern → FTE)",
    company: "Confidential (Mira Road, Mumbai)",
    type: "Internship",
    mode: "Onsite",
    location: "Mira Road, Mumbai",
    postedOn: "2025-08-01",
    exp: "0–1 yr",
    highlights: ["Selenium WebDriver • SQL • Cypress (plus)"],
    shareKey: "java-automation-intern-mira-road",
  },
  {
    id: "eclerx-analyst-qa",
    bannerImage: "/live-jobs_images/jobs_image/eclerx-analyst-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Analyst (QA focus across trade lifecycle)",
    company: "eClerx Financial Markets",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    shareKey: "analyst-eclerx-qa",
  },
  {
    id: "notion-tech-qa-tester-fresher",
    bannerImage:
      "/live-jobs_images/jobs_image/notion-tech-qa-tester-fresher.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Tester (Fresher/Junior)",
    company: "Notion Technologies",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    shareKey: "qa-tester-notion",
  },
  {
    id: "accuknox-qa-trainee-cloud-security",
    bannerImage:
      "/live-jobs_images/jobs_image/accuknox-qa-trainee-cloud-security.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "QA Trainee – Functional & Performance (Cloud Security)",
    company: "AccuKnox",
    type: "Internship",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    shareKey: "qa-trainee-accuknox",
  },
  {
    id: "pg-data-science-internship",
    bannerImage:
      "/live-jobs_images/jobs_image/pg-data-science-internship.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Internship – Data Science",
    company: "Procter & Gamble",
    type: "Internship",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    shareKey: "pg-data-science-intern",
  },
  {
    id: "pg-analytics-insights-summer-intern",
    bannerImage:
      "/live-jobs_images/jobs_image/pg-analytics-insights-summer-intern.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Summer Internship – Analytics & Insights",
    company: "Procter & Gamble",
    type: "Internship",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    shareKey: "pg-analytics-insights-intern",
  },
  {
    id: "jio-get-5g-assurance",
    bannerImage: "/live-jobs_images/jobs_image/jio-get-5g-assurance.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Graduate Engineer Trainee – 5G R&D (Assurance)",
    company: "Jio (Reliance)",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai RCP",
    postedOn: "2025-08-01",
    shareKey: "jio-get-5g-assurance",
  },
  {
    id: "alta-exchange-bi-analyst",
    bannerImage: "/live-jobs_images/jobs_image/alta-exchange-bi-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Business Intelligence Analyst",
    company: "Alta Exchange",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    exp: "2–3 yrs",
    highlights: ["SQL • Python • Looker/Tableau/Power BI"],
    shareKey: "bi-analyst-alta-exchange",
  },
  {
    id: "alta-exchange-bi-analyst-intern",
    bannerImage:
      "/live-jobs_images/jobs_image/alta-exchange-bi-analyst-intern.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Business Intelligence Analyst – Intern",
    company: "Alta Exchange",
    type: "Internship",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    shareKey: "bi-analyst-intern-alta-exchange",
  },
  {
    id: "blenheim-chalcot-data-engineer",
    bannerImage:
      "/live-jobs_images/jobs_image/blenheim-chalcot-data-engineer.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Data Engineer",
    company: "Blenheim Chalcot India",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    highlights: ["PostgreSQL • Python • ELT • Cloud"],
    shareKey: "data-engineer-blenheim-chalcot",
  },
  {
    id: "blenheim-chalcot-jr-web-automation-qa",
    bannerImage:
      "/live-jobs_images/jobs_image/blenheim-chalcot-jr-web-automation-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Jr Web Automation QA Engineer (Python/Selenium)",
    company: "Blenheim Chalcot India",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    shareKey: "jr-web-automation-qa-blenheim-chalcot",
  },
  {
    id: "manthan-tec-trainee-test-engineer",
    bannerImage:
      "/live-jobs_images/jobs_image/manthan-tec-trainee-test-engineer.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee Test Engineer",
    company: "Manthan Tec Consultancy Services",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-08-01",
    shareKey: "trainee-test-engineer-manthan-tec",
  },
  {
    id: "allerin-qa-engineer-navi-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/allerin-qa-engineer-navi-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Engineer",
    company: "Allerin",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    shareKey: "qa-engineer-allerin",
  },
  {
    id: "allerin-trainee-business-analyst",
    bannerImage:
      "/live-jobs_images/jobs_image/allerin-trainee-business-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee Business Analyst",
    company: "Allerin",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    shareKey: "trainee-business-analyst-allerin",
  },
  {
    id: "axs-solutions-software-tester-intern",
    bannerImage:
      "/live-jobs_images/jobs_image/axs-solutions-software-tester-intern.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester Intern",
    company: "Axs Solutions",
    type: "Internship",
    mode: "Onsite",
    location: "Mumbai – Chembur (W)",
    postedOn: "2025-10-24",
    exp: "0–1 yr",
    highlights: [
      "SDLC/STLC & Bug Life Cycle",
      "Manual & basic Automation (Web)",
      "DB testing, test cases & scenarios, bug reporting",
      "Tools: Jira / Mantis / Bugzilla",
      "Automation: QTP / IBM RFT / Selenium",
      "Preferred: ISTQB, JMeter knowledge",
    ],
    responsibilities: [
      "Write scenarios & test cases; execute system, integration, regression, UAT",
      "Prepare & maintain testing documents; report defects",
    ],
    applyEmail: "infoaxs@axs-solutions.com",
    tags: ["Job Alert", "Internship"],
    bannerImageAlt: "Axs Solutions — Software Tester Intern",
    shareKey: "software-tester-intern-axs-solutions-2025",
  },
  {
    id: "vishleshan-software-tester",
    bannerImage:
      "/live-jobs_images/jobs_image/vishleshan-software-tester.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester",
    company: "Vishleshan",
    type: "Full-time",
    mode: "Onsite",
    location: "India (TBA)",
    postedOn: "2025-10-24",
    highlights: ["Manual testing", "Defect reporting & documentation"],
    bannerImageAlt: "Vishleshan — Software Tester",
    tags: ["We’re Hiring"],
    shareKey: "software-tester-vishleshan-2025",
  },
  {
    id: "aarav-oracle-database-admin",
    bannerImage:
      "/live-jobs_images/jobs_image/aarav-oracle-database-admin.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Oracle Database Administrator",
    company: "Aarav Global Products",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-10-24",
    exp: "5+ yrs",
    highlights: [
      "Oracle 12c/19c, RAC, ASM, Flashback, RMAN, Data Guard, GoldenGate",
      "PR–DR switch, patching & upgrades; backup & recovery; cloning",
      "Performance tuning; SQL proficiency; security (encryption, Vault, wallet)",
      "Linux/Unix: shell scripting, kernel analysis, networking",
      "Certified DBA; mission-critical DB ops",
    ],
    responsibilities: [
      "Own Data Guard, RMAN strategies & large-DB administration",
      "RAC install & maintenance; migration & upgrades; security implementation",
    ],
    bannerImageAlt: "Aarav Global — Oracle DBA",
    tags: ["Job Alert"],
    shareKey: "oracle-dba-aarav-global-2025",
  },
  {
    id: "qa-manual-engineer-noida",
    bannerImage:
      "/live-jobs_images/jobs_image/qa-manual-engineer-noida.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "QA Manual Engineer",
    company: "Orane",
    type: "Full-time",
    mode: "Onsite",
    location: "Noida",
    postedOn: "2025-10-24",
    exp: "2+ yrs",
    highlights: [
      "Continuous learning & upskilling",
      "Fast-track growth for high performers",
      "Competitive salary",
    ],
    applyEmail: "careers@orane.in",
    bannerImageAlt: "Orane — QA Manual Engineer (Noida)",
    tags: ["Job Alert"],
    shareKey: "qa-manual-engineer-orane-noida-2025",
  },
  {
    id: "senior-qa-engineer-ahmedabad",
    bannerImage:
      "/live-jobs_images/jobs_image/senior-qa-engineer-ahmedabad.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Senior QA Engineer (Manual & Automation)",
    company: "Converge Solution",
    type: "Full-time",
    mode: "Onsite",
    location: "Ahmedabad",
    postedOn: "2025-10-24",
    exp: "4–7 yrs",
    highlights: [
      "Test plans & detailed test cases",
      "Build/maintain automation frameworks (Selenium/JUnit/TestNG)",
      "Manual + Automation ownership",
    ],
    responsibilities: [
      "Design, execute, and manage manual & automated tests",
      "Develop and maintain automation suites; performance testing",
    ],
    applyEmail: "hr@convergesolution.com",
    contacts: ["+91 77780 59923"],
    bannerImageAlt: "Senior QA Engineer — Ahmedabad",
    tags: ["Job Alert"],
    shareKey: "senior-qa-engineer-converge-ahmedabad-2025",
  },
  {
    id: "accenture-quality-engineer-tester",
    bannerImage:
      "/live-jobs_images/jobs_image/accenture-quality-engineer-tester.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Engineer (Tester)",
    company: "Accenture",
    type: "Full-time",
    mode: "Onsite",
    location: "India (various)",
    postedOn: "2025-10-24",
    highlights: [
      "Full-stack quality across lifecycle",
      "Security, API, regression testing",
      "Automation strategy & scripts",
      "Data & environment configuration",
      "Code reviews; defect monitoring & reporting",
    ],
    responsibilities: [
      "Collaborate cross-functionally; convert requirements to test plans",
      "Design & execute test cases; identify/report/track defects",
      "Develop & maintain automation; conduct performance testing",
      "Contribute solutions; stay current with testing best practices",
    ],
    bannerImageAlt: "Accenture — Quality Engineer (Tester)",
    tags: ["Placement Update", "Job Alert"],
    shareKey: "quality-engineer-tester-accenture-2025",
  },
  {
    id: "allerin-trainee-test-engineer",
    bannerImage:
      "/live-jobs_images/jobs_image/allerin-trainee-test-engineer.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee Test Engineer",
    company: "Allerin",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    highlights: ["Testing methodologies", "Docs", "UAT"],
    shareKey: "trainee-test-engineer-allerin",
  },
  {
    id: "thane-internship-manual-automation-qa",
    bannerImage:
      "/live-jobs_images/jobs_image/thane-internship-manual-automation-qa.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Internship – Manual & Automation Test Engineer",
    company: "Confidential (Thane – Hiranandani)",
    type: "Internship",
    mode: "Onsite",
    location: "Thane",
    postedOn: "2025-08-01",
    salary: "₹20,000–₹25,000 stipend",
    shareKey: "internship-qa-thane",
  },
  {
    id: "automate-buddy-software-tester-navi-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/automate-buddy-software-tester-navi-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Software Tester",
    company: "Automate Buddy",
    type: "Full-time",
    mode: "Onsite",
    location: "Navi Mumbai",
    postedOn: "2025-08-01",
    exp: "0–2 yrs",
    shareKey: "software-tester-automate-buddy",
  },
  {
    id: "cognizant-trainee-junior-data-analyst",
    bannerImage:
      "/live-jobs_images/jobs_image/cognizant-trainee-junior-data-analyst.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title:
      "Trainee/Junior Data Analyst (CDM/PV + GenAI)",
    company: "Cognizant",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    shareKey: "trainee-junior-data-analyst-cognizant",
  },
  {
    id: "cuddles-foundations-qa-engineer-mumbai",
    bannerImage:
      "/live-jobs_images/jobs_image/cuddles-foundations-qa-engineer-mumbai.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Quality Assurance Engineer (IT)",
    company: "Cuddles Foundations",
    type: "Full-time",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2025-08-01",
    exp: "2+ yrs",
    applyLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSeoTM7EPeczW3ZlGTFDLeWjS0ddGX3hiCRrPlcoYH8faH4hBQ/viewform",
    venue:
      "Unit 5, 2nd Floor, Brady Gladys Plaza, 1/447, Senapati Bapat Marg, Lower Parel, Mumbai 400013",
    shareKey: "qa-engineer-cuddles-mumbai",
  },
  {
    id: "instinct-innovations-automation-walkin-mumbai-2024-10-05",
    bannerImage:
      "/live-jobs_images/jobs_image/instinct-innovations-automation-walkin-mumbai-2024-10-05.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Automation Tester (Walk-in: 5 Oct 2024)",
    company: "Instinct Innovations",
    type: "Walk-in",
    mode: "Onsite",
    location: "Mumbai",
    postedOn: "2024-10-01",
    eventDate: "2024-10-05",
    timeWindow: "11:00 AM – 12:00 PM",
    venue:
      "D Wing, 7th floor, Lotus Corporate Park, Western Express Hwy, Jogeshwari East, Mumbai 400063",
    highlights: ["Java/JS • Selenium/Playwright • 1–4 yrs"],
    shareKey: "automation-walkin-instinct-innovations",
  },
  {
    id: "acuity-trainee-quality-analyst-hyd",
    bannerImage:
      "/live-jobs_images/jobs_image/acuity-trainee-quality-analyst-hyd.jpg",
    imageFallback: "/live-jobs_images/jobs_image/cdpl-no-job-image-bag-icon.jpg",
    title: "Trainee Quality Analyst (Walk-in)",
    company: "Acuity Software Technologies",
    type: "Walk-in",
    mode: "Onsite",
    location: "Hyderabad",
    postedOn: "2024-10-01",
    eventDate: "2024-10-07",
    timeWindow: "11:30 AM – 4:00 PM",
    venue:
      "#A701 The Platina, Gachibowli, Miyapur Rd (Next to Radisson Hotel), Hyderabad 500032",
    highlights: ["Manual + Automation • 3 openings"],
    shareKey: "trainee-qa-acuity-walkin",
  },
];
