// =============================
// components/our-team/data.ts
// =============================
import type { TeamMember, Trainer, TeamLeaders } from "./types";


export const BRAND = "#ff8c00"; // Cinute Digital brand


export const teamLeaders: TeamLeaders[] = [
    {
        id: "1",
        name: "Sandeep Maske",
        title: "Founder & Chief Mentor",
        role: "Leadership",
        experience: "20+ years",
        specialization: "QA Strategy & Leadership",
        expertise: ["Software Testing", "Automation", "Career Mentorship"],
        bio: "EdTech leader with a decade of experience enabling learners to build industry-ready skills through hands-on projects and mentor-led learning.",
        achievements: [
            "Founded Testriq in 2010",
            "Scaled company to 50+ employees",
            "ISTQB Advanced Level Certified",
            "Speaker at 20+ industry conferences",
        ],
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/sandeep-maske-img.webp",
        linkedin: "https://www.linkedin.com/in/sandeepmaske",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Mentored career transitions", "ISO-aligned delivery"],

    },
    {
        id: "2",
        name: "Santosh Kakade",
        title: "QA & Digital Solutions",
        role: "Operations",
        experience: "14+ years",
        specialization: "QA Strategy & Digital Solutions",
        expertise: ["QA", "Digital Solutions"],
        bio: "Santosh Kakade, With 17+ years in QA & digital solutions, lead TESTRIQ QA Lab & Cinute Digital, delivering top-tier testing services and upskilling professionals in tech.",
        achievements: [
            "Led 100+ automation projects",
            "Expert in Selenium, Cypress, Playwright",
            "DevOps and CI/CD specialist",
            "Published 15+ technical articles",
        ],
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/Santosh_Kakade.webp",
        linkedin: "https://www.linkedin.com/in/santoshkakade/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Mentored career transitions", "ISO-aligned delivery"],

    },
    {
        id: "3",
        name: "Goutam Mishra",
        title: "Head of QA and BD",
        role: "Software Testing & BD",
        experience: "20+ years",
        specialization: "Software Testing & BD",
        expertise: ["Software Testing", "BD"],
        bio: "Goutam Mishra, With 20+ years in tech, excel in QA, testing, and project management, mentoring QA professionals while ensuring top-tier software quality across platforms.",
        achievements: [
            "Designed QA processes for 200+ projects",
            "ISTQB Expert Level Certified",
            "Reduced bug leakage by 95%",
            "Mentored 30+ junior testers",
        ],
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/Goutam_Mishra.webp",
        linkedin: "https://www.linkedin.com/in/goutam-mishra-96194117/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Mentored career transitions", "ISO-aligned delivery"],

    },
    {
        id: "4",
        name: "Shoeb Shaikh",
        title: "Head - Learning and Development",
        role: "Software Testing and Data Science Expert",
        experience: "14+ years",
        specialization: "Software Testing and Data Science Expert",
        expertise: ["Software Testing", "Data Science Expert"],
        bio: "Shoeb Shaikh is a seasoned Software Testing and Data Science Expert and a Mentor with over 14 years of experience in the field. Specialist in designing and managing processes, and leading high-performing teams to deliver impactful results.",
        achievements: [
            "Designed & Delivered 50+ QA and Data Science training programs",
            "Trained professionals in QA and Data Science",
            "ISTQB Certified Test Manager (Selenium, Pytest, API, DBMS)",
            "Led L&D initiatives in academic and corporate environments"
        ],
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/ShoebShaikh.webp",
        linkedin: "https://www.linkedin.com/in/ishaikhshoeb/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Mentored career transitions", "ISO-aligned delivery"],

    }, {
        id: "5",
        name: "Ashish Shetty",
        title: "Business Intelligence & Data Analytics Specialist | L&D Expert",
        role: "Business Intelligence & Data Analytics Specialist | L&D Expert",
        experience: "11+ years",
        specialization: "QA Strategy & Leadership",
        expertise: ["Business Intelligence", "learning and development professional"],
        bio: "Ashish Shetty is a seasoned Business Intelligence and learning and development professional with over 11 years of experience empowering students and professionals to unlock career success through data-driven skills. Specializing in Power BI, Tableau, and Prompt Engineering, Ashish is known for delivering practical, high-impact workshops and training programs across academic and corporate sectors.",
        achievements: [
            "Trained students & professionals in BI, ML, and Analytics",
            "Delivered 50+ workshops and national-level programs",
            "Keynote speaker at leading conferences and UGC events",
            "Designed industry-certified training and faculty development courses",
            "Advanced Data Science & Machine Learning certified"
        ],
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/AshishShetty.png",
        linkedin: "https://www.linkedin.com/in/profashishshetty/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Mentored career transitions", "ISO-aligned delivery"],

    },
]

export const teamData: TeamMember[] = [

    {
        id: "1",
        name: "Aakash Yadav",
        title: "QA Head, R&D Innovation Specialist",
        role: "QA Head, R&D Innovation Specialist",
        expertise: ["Selenium", "Playwright", "API Testing", "CI/CD"],
        bio: "Leads QA and R&D initiatives, driving innovation, improving testing frameworks, and ensuring high-quality, future-ready software solutions.",
        location: "Pune, India",
        avatar: "/Team/aakash-yadav.webp",
        linkedin: "https://www.linkedin.com/in/aakashyadav9890/",
    },
    {
        id: "2",
        name: "Siddharth Desai",
        title: "Automation Architect",
        role: "Automation Architect",
        expertise: ["Selenium", "Playwright", "API Testing", "CI/CD"],
        bio: "Designs and implements intelligent automation frameworks, optimizing workflows and ensuring efficient, scalable, and high-quality software delivery.",
        location: "Pune, India",
        avatar: "/Team/siddharth-desai.webp",
        linkedin: "https://www.linkedin.com/in/siddharth-desai-852996201/",
    },
    {
        id: "3",
        name: "Prathamesh Maske",
        title: "IoT and Mobile QA Architect",
        role: "IoT and Mobile QA Architect",
        expertise: ["Python", "ML", "NLP", "Generative AI"],
        bio: "Specializes in ensuring seamless quality across IoT and mobile ecosystems through advanced testing strategies, automation, and performance optimization.",
        location: "Remote, India",
        avatar: "/Team/prathmesh-maske.webp",
        linkedin: "https://www.linkedin.com/in/prathameshmaske/",
    },
    {
        id: "4",
        name: "Sujay Ambelkar",
        title: "Sr. QA Specialist",
        role: "Sr. QA Specialist",
        expertise: ["QA Strategy", "Test Architecture", "Agile"],
        bio: "Advises on QA strategy, governance, and enterprise-grade testing practices to align outcomes with hiring partner expectations.",
        location: "Bengaluru, India",
        avatar: "/Team/sujay-ambelkar.png",
        linkedin: "https://www.linkedin.com/in/sujay-ambelkar-ab2770145/",
    },
    {
        id: "5",
        name: "Pooja Katkar",
        title: "Test Lead",
        role: "Test Lead",
        expertise: ["Student Success", "Placements", "Admissions"],
        bio: "Leads end-to-end testing processes, coordinating teams and strategies to ensure flawless, high-quality software delivery.",
        location: "Mumbai, India",
        avatar: "/Team/dummy-image.avif",
        linkedin: "https://www.linkedin.com/in/pooja-katkar-737b3525a/",
    },
    {
        id: "6",
        name: "Prakash Mishra",
        title: "Lead Software Engineer",
        role: "Lead Software Engineer",
        expertise: ["Student Success", "Placements", "Admissions"],
        bio: "Drives software development initiatives, leading teams to build robust, scalable, and high-performance solutions with a focus on quality and innovation.",
        location: "Mumbai, India",
        avatar: "/Team/prakash-mishra.png",
        linkedin: "https://www.linkedin.com/in/prakashmmishra/",
    },
    {
        id: "7",
        name: "Pravin Kodag",
        title: "IT Administrator",
        role: "IT Administrator",
        expertise: ["Student Success", "Placements", "Admissions"],
        bio: "Manages and maintains IT infrastructure, ensuring secure, efficient, and reliable systems that support seamless business operations.",
        location: "Mumbai, India",
        avatar: "/Team/pravin-kodag.jpg",
        linkedin: "https://www.linkedin.com/in/pravin-kodag-83a717189/",
    },
    {
        id: "8",
        name: "Elvita Gomes",
        title: "HR Specialist",
        role: "HR Specialist",
        expertise: ["Student Success", "Placements", "Admissions"],
        bio: "Champions talent acquisition, onboarding, and engagement; streamlines HR operations, ensures compliance, and fosters a positive, high-performance culture.",
        location: "Mumbai, India",
        avatar: "/Team/elvita-gomes.webp",
        linkedin: "https://www.linkedin.com/in/elvita07/"
    },

];

export const trainers: Trainer[] = [
    {
        id: 1,
        name: "Teshoo Rai",
        role: "Quality Analysis Engineer",
        avatar: "/Trainers_image/TeshooRai.png",
        bio: "A highly skilled Quality Analysis Engineer and Corporate Trainer, specialising in Software Development Life Cycle (SDLC) and Software Test Life Cycle (STLC).",
        yearsExp: 5,
        rating: 4.9,
        specialties: ["Corporate Trainer", "Software Development Life Cycle (SDLC)", "Software Test Life Cycle (STLC)", "Java Automation", "Selenium"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "http://linkedin.com/in/teshoo-rai-b56179237"
    },
    {
        id: 2,
        name: "Pooja Bombatkar",
        role: "Senior QA Mentor",
        avatar: "/Trainers_image/PoojaBombatkar.png",
        bio: "An ISTQB certified tester with more than 8-years of comprehensive experience of working in the field of software testing.",
        yearsExp: 8,
        rating: 4.9,
        specialties: ["Manual Testing", "Automation Testing", "API Testing", "Functional Testing", "System Testing"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "https://www.linkedin.com/in/pooja-shinde-475076122",
    },
    {
        id: 3,
        name: "Vaibhav Kakade",
        role: "Quality Analysis Engineer",
        avatar: "/Trainers_image/VaibhavKakade.png",
        bio: "A Manual Tester in TESTRIQ QA LLP and also as Corporate Trainer with CDPL. With a focused career in training and development.",
        yearsExp: 4,
        rating: 4.9,
        specialties: ["Manual Testing", "DBMS", "MySQL", "CI/CD", "Test Strategy"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "https://www.linkedin.com/in/vaibhav-kakade-565bb6207",
    },
    {
        id: 4,
        name: "Rehmat Shaikh",
        role: "Data Science Trainer",
        avatar: "/Trainers_image/RehmatShaikh.png",
        bio: "A visionary data scientist dedicated to unlocking the potential of data to drive informed decision-making and spark innovation. With a strong foundation in machine learning and business intelligence.",
        yearsExp: 2,
        rating: 4.9,
        specialties: ["Data Science", "Analytics", "Training Programs"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "https://www.linkedin.com/in/rehmat-shaikh-60a023324",
    },
    {
        id: 5,
        name: "Cezzane Khan",
        role: "Data Science Trainer",
        avatar: "/Trainers_image/CezzaneKhan.png",
        bio: "Khan Cezzane is a dedicated and innovative Data Science Trainer committed to empowering individuals and organizations through comprehensive data analytics education. With a strong foundation in artificial intelligence and data science.",
        yearsExp: 2,
        rating: 4.9,
        specialties: ["Data Science", "Python", "SQL", "Power BI", "Tableau "],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "https://www.linkedin.com/in/khan-cezzane",
    },
];
