import type { Trainer } from "./types";


export const trainers: Trainer[] = [
    {
        id: "t1",
        name: "Aarav Kulkarni",
        title: "Senior QA Automation Lead",
        location: "Pune, India",
        avatar: "/images/person_image.jpg",
        yearsExp: 9,
        skills: ["Selenium", "Playwright", "Cypress", "API Testing", "Java", "CI/CD"],
        certifications: ["ISTQB", "AWS Cloud Practitioner"],
        bio: "Leads enterprise-grade automation frameworks and trains testers to build scalable, maintainable test suites.",
        socials: { linkedin: "https://www.linkedin.com/" },
    },
    {
        id: "t2",
        name: "Isha Mehta",
        title: "Manual + API Testing Mentor",
        location: "Bengaluru, India",
        avatar: "/images/person_image.jpg",
        yearsExp: 7,
        skills: ["Manual Testing", "Postman", "JMeter", "Agile QA", "TestRail"],
        certifications: ["Scrum Master"],
        bio: "Focuses on requirements analysis, test design, and API-first quality strategies for fast-moving teams.",
        socials: { linkedin: "https://www.linkedin.com/" },
    },
    {
        id: "t3",
        name: "Rudra Sharma",
        title: "SDET | JavaScript Specialist",
        location: "Remote",
        avatar: "/images/person_image.jpg",
        yearsExp: 6,
        skills: ["TypeScript", "Playwright", "Cypress", "BDD", "Docker"],
        certifications: ["AZ-900"],
        bio: "Teaches modern SDET skills: TypeScript-first testing, BDD, containerized pipelines, and quality gates.",
    },
    {
        id: "t4",
        name: "Nisha Verma",
        title: "Data Science & ML Coach",
        location: "Hyderabad, India",
        avatar: "/images/person_image.jpg",
        yearsExp: 8,
        skills: ["Python", "Pandas", "Scikit-learn", "EDA", "MLOps"],
        certifications: ["TensorFlow Developer"],
        bio: "Guides learners to build job-ready ML portfolios with clean EDA, robust baselines, and clear storytelling.",
    },
    {
        id: "t5",
        name: "Kabir Singh",
        title: "Performance Testing Expert",
        location: "Noida, India",
        avatar: "/images/person_image.jpg",
        yearsExp: 10,
        skills: ["JMeter", "k6", "Gatling", "Monitoring", "Grafana", "SRE"],
        certifications: ["CKA"],
        bio: "Specializes in perf testing strategies that mirror production realities with actionable insights.",
    },
    {
        id: "t6",
        name: "Meera Rao",
        title: "Mobile QA | App Automation",
        location: "Mumbai, India",
        avatar: "/images/person_image.jpg",
        yearsExp: 5,
        skills: ["Appium", "Android", "iOS", "XCUITest", "Test Strategy"],
        certifications: ["ISTQB Advanced"],
        bio: "Helps teams ship stable mobile apps with cross-platform coverage and pragmatic automation.",
    },
];
